### ISSUE TITLE
是否可以加入个功能

### ISSUE THREAD

**Issue by lauixData** [domgoer/gotask#1]
需要一个 按年 指定几月几号 几点执行的 功能

**Comment by domgoer** [comment]
你可以使用monthtask，在执行时判断月份？按年执行

**Comment by lauixData** [comment]
@domgoer 是个办法，如果你能集成那是最好的了。

**Comment by domgoer** [comment]
感谢建议，后续可能会添加。你可以暂时先用monthtask实现这个功能，效果上应该不会有差别

**Comment by domgoer** [comment]
现在已经支持这个功能了，可以拉1.4版本
https://github.com/domgoer/gotask/blob/master/task.go#L149

**Comment by lauixData** [comment]
@domgoer 收到，我在 https://github.com/yehuio/Coot 这个项目里采用了你的组件，有兴趣可以加微信聊一聊！文档里二维码
